### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by leobalter** [mozillabrasil/womoz.mozillabrasil.org.br#7]
@soapdog, já montou vagrant para Wordpress? 

Seria bacana a gente ter um vagrant com uma instância do wordpress pronta (e igual ao que teriamos em produção) para mexer no tema.

Extra: ansible

**Comment by cynthiapereira** [comment]
@leobalter e @cstipkovic,
A box para desenvolvimento com WordPress está pronto e disponível [nesse repositório](https://github.com/mozillabrasil/vagrant-wordpress).
Há instruções de como instalar e ativar o este tema/repositório diretamente na box. :)

**Comment by cstipkovic** [comment]
:+1:

**Comment by leobalter** [comment]
Que maravilha!
