### ISSUE TITLE
Review WoMoz [layout]

### ISSUE THREAD

**Issue by WagnerMoreira** [mozillabrasil/womoz.mozillabrasil.org.br#9]
#### 1 - Menu
- Eu melhoraria o css dele, cada item do menu parece um botão então eu sugiro fazer uma interação no botão inteiro, por exemplo quando mudamos o background do botão neste tipo de menu [aqui](https://www.dropbox.com/s/vef4x0frwvn2w4x/Screenshot%202015-05-23%2014.18.53.png?dl=0)
e atualmente nós só mudamos a cor do texto, que é um comportamento padrão em menus que não se parecem com botões, construidos só com os links como esse [aqui](https://www.dropbox.com/s/um6vrbhnu406dad/Screenshot%202015-05-23%2014.21.09.png?dl=0)
*Essa observação é mais pra gosto visual do que qualquer outra coisa, se não concordarem não vou chorar XD*

#### 2 - Projetos Relacionados
- Nesta seção eu acredito que deveriamos linkar cada projeto,  as imagens estão sem links

#### 3 - O que é WoMoz?
- Essa seção está ótima <3 eu só reparei uma coisa, quando se clica no [faça parte] ele fica sublinhado, eu tiraria isso

#### 4 - Projetos do WoMoz
- Aqui eu acho que deveria ter um separador vertical entre as colunas ou mais espaço entre elas, se tiverem items com bastante texto vai ficar um tanto desconfortável pra leitura, segue [exemplo](https://www.dropbox.com/s/0atr7f7zzgwwvov/Screenshot%202015-05-23%2015.03.19.png?dl=0)
- E por fim ``text-align: center`` nos títulos

#### 5 - Novidades no Brasil
- Eu adicionaria transitions nesse hover dos items, e os likes vão funcionar como? parece que ainda não está feito essa feature, entrando no post só dá pra comentar. Minha sugestão sobre isso é salvar no localstorage ou cookie pra pessoa não ficar dando varios likes.
- Acho que o link do post deveria estar no item inteiro, não só no titulo dele, eu tentei clicar na imagem esperando que abrisse o post, acho que a maioria dos usuários tem esse comportamento.

#### 6 - O Grupo
- Por mim isso está ótimo, eu não mudaria nada aqui exceto a descrição (Conheça algumas **voluntárias** do WoMoz) ja tem o Rodrigo de homem ali então mudar pra **voluntários**.
- Acho valido adicionar alguns links como blog/portfolio/e-mail etc dos integrantes abaixo do avatar deles

#### 7 - Faça parte do WoMoz
- O que vamos mostrar ali a esquerda do form de cadastro?
- Na descrição da seção ta escrito "contruir" só corrigir pra construir(Eu sempre digito errado pela pressa, acontece muito)

#### 8 - Paginas internas
- Eu percebo que quando você está nas paginas internas e não existem eventos agendados(situação atual) sobra muito espaço do lado direito da pagina, acho que podemos esconder esse widget de eventos quando não houver nenhum agendado, e deixar o conteúdo da pagina centralizado

**Comment by halcance** [comment]
Tópico segue no issue https://github.com/mozillabrasil/womoz.mozillabrasil.org.br/issues/10
